### ISSUE TITLE
[功能建议] 对话conversation 改进建议：允许局部应用主题，新增主题类型narration（旁白）

### ISSUE THREAD

**Issue by luoxiawuchen** [TabooLib/chemdah#52]
**前言：**
目前，Chemdah对话模块 - conversation 似乎没有**旁白**这种设定，玩家与NPC进行对话时，无法插入类似旁白的描述补充
例如：
A：你好
回复项：你好，请问你是？
A：怎么？不认识我了？
回复项：嗯？？？
旁白：（你在脑海中搜寻着有关这名陌生人的记忆，但一无所获）
回复项：抱歉，我确实忘了
A：...
回复项：...

这样设置会让对话变得更为灵活，以完善RPG的叙事需要，可以分以下两步实现上述效果。

1、目前对话的主题主要是依靠**选项**实现的，但选项似乎是应用于整个文件的，能否让选项局部应用那？
```
__option__:
  theme: 'chat'
  title: 'Mr.{name}'

```
单个对话选项的优先级高于全局选项，例如：
```
conversation_0:
_**__option__:
  theme: 'chat'
  title: 'Mr.{name}'**_
  npc id: 'adyeshach test2'
  npc:
    - 'Hi! {{ sender }}.'
    - 'I''m conversation tester for Chemdah.'
  player:
    - reply: 'Hi!'
      then: |
        goto conversation_0_1
    - if: permission admin
      reply: 'You know Mr.Black?'
      then: |
        talk "Yes, I know him very well."
```

```
conversation_0_1:
_**__option__:
  theme: 'chest'
  title: '233'**_
  npc:
    - 'Look! A new conversation structure.'
  player:
    - reply: 'Cool!'
      then: |
        set game true
        goto conversation_0_2
    - reply: 'Not bed.'
      then: |
        talk "All right, see you later."
```

2、在与NPC对话过程中，其实会有一些关于旁白的描写补充，新增**narration旁白**主题，可以增强Chemdah对话的故事性。

预设可以是这样（删除了{title}/NPC名称标题）：
```
theme-chat:
  format:
    - ' '
    - ' '
    - ' '
    - '  &f" &7{npc_side}&r &f"'
    - ' '
    - '  {reply}'
    - ' '
  select:
    reply:
      1: '&7▶ &f&n{player_side}&r &8(&6&lF&8)'
      0: '&8▶ &7{player_side}&r   &r'
    sound:
      name: ENTITY_EXPERIENCE_ORB_PICKUP
      p: 2
      v: 0
  sound:
    name: ENTITY_ITEM_PICKUP
    # Pitch
    p: 1
    # Volume
    v: 0
  # The reply content is displayed when the NPC is speaking
  talking: '    &8...'
  # Text animation
  animation: true
  # Text appearance speed
  speed: 1
  # Blank line between each conversation
  space-line: 30
  # Hover Text on the reply
  hover-text: true
  # Use the scroll wheel to switch the reply content
  use-scroll: false
  # Display the reply "block" to one line
  single-line:
    enable: true
    # Character length per line
    auto-swap: 36
    # Using only spaces characters
    reply-separator: ' '
```

**最后，感谢坏黑大佬的耐心阅读**
