### ISSUE TITLE
[功能建议] goto语句增强，允许goto至Switch框架对话类型

### ISSUE THREAD

**Issue by luoxiawuchen** [TabooLib/chemdah#53]
请问可以允许框架generic的对话，通过kether脚本goto跳转至框架为Switch的对话吗？
这样可以给对话编写带来更多可能，同时让对话编写更精简（在某些情况下）
例如：

**不允许goto跳转时：**

```
开头switch: 
  npc id: 'adyeshach test'
  when:
    - if: perm test
      open: 演示对话-无法goto

演示对话-无法goto:
  npc: |
    npc说的话...
  player:
    - if: 条件1
      reply: **相同回复项**
      then: goto 对话1
    - if: 条件2
      reply: **相同回复项**
      then: goto 对话2
    - if: 条件3
      reply: **相同回复项**
      then: goto 对话3
    - if: 条件4
      reply: **相同回复项**
      then: goto 对话4
    - if: 条件5
      reply: **相同回复项**
      then: goto 对话5

对话1:
  npc: |
    npc说的话...
  player:
      reply: ...
对话2: 略
对话3: 略

```

**允许goto跳转时：**
```
开头switch: 
  npc id: 'adyeshach test'
  when:
    - if: perm test
      open: 演示对话-允许goto

演示对话-允许goto:
  npc: |
    npc说的话...
  player:
      reply: ...
      then: goto switch判定条件

switch判断条件: 
  when:
    - if: 条件1
      open: 对话1
    - if: 条件2
      open: 对话2
    - if: 条件3
      open: 对话3
    - if: 条件4
      open: 对话4
    - if: 条件5
      open: 对话5

对话1:
  npc: |
    npc说的话...
  player:
      reply: ...
对话2: 略
对话3: 略
...

这样一来，在需要进行多条件判定时，
对比不能被goto到switch的方案，此方案下，reply: **相同回复项**就可以被省略，使得对话语句更精简
可读性也得到了提高。

```
